/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package OutboundExample;

import software.amazon.awssdk.services.connect.ConnectClient;

import java.util.Map;

public class App {
    public static void main(String[] args) {
        var client = ConnectClient.create();
        var contactAttributes = Map.ofEntries(
                Map.entry("ExampleContactAttributeKey", "ExampleContactAttributeValue"),
                Map.entry("MoreKey", "MoreValue")
        );
        client.startOutboundVoiceContact(call ->
            call.attributes(Map.ofEntries())
                // https://docs.aws.amazon.com/connect/latest/APIReference/API_StartOutboundVoiceContact.html#connect-StartOutboundVoiceContact-request-ClientToken
                .clientToken("unique string for idempotent requests")
                .sourcePhoneNumber("+12065550100")
                .instanceId("c2e9dc6f-3f69-40e2-b0ec-f78d0c62bee6")
                .contactFlowId("ae4e2be3-5541-4c57-9738-217052e61eb3")
                .destinationPhoneNumber("+12065550101")
                .attributes(contactAttributes)
        );
    }
}
